name: Python Pipeline

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: action/checkout@v2
       - run: python hello.py
    
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/checkout@upload-artifact@v2
        with:
          name: hello
          path: . 
    
